apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: l3moni-nginx-deployment
  labels:
    app: l3moni-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: l3moni-nginx
  template:
    metadata:
      labels:
        app: l3moni-nginx
    spec:
      containers:
      - name: l3moni-blog-nginx
        image: l3moni.azurecr.io/l3moni-blog:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: l3moni-nginx-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: l3moni-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/hostname : lemoni.cloud
spec:
  rules:
  - host: blog.lemoni.cloud
    http:
      paths:
        - path: /
          pathType : Prefix
          backend:
            service:
              name: l3moni-nginx-service
              port:
                number: 80
  - host: lemoni.cloud
    http:
      paths:
        - path: /
          pathType : Prefix
          backend:
            service:
              name: l3moni-nginx-service
              port:
                number: 80